fix: poc for new approach

diff --git a/apps/web/Dockerfile b/apps/web/Dockerfile
--- a/apps/web/Dockerfile
+++ b/apps/web/Dockerfile
@@ -1,23 +1,6 @@
-# Use the official Node.js image as a base image for the installer stage
 FROM node:18-alpine AS installer
-
-# Install system dependencies and tools, including sudo
-RUN apk add --no-cache --virtual .build-deps \
-        g++ \
-        gcc \
-        libgcc \
-        libstdc++ \
-        linux-headers \
-        make \
-        python3 \
-        cmake \
-        sudo \
-        openssl
-
-# Enable corepack and prepare pnpm
 RUN corepack enable && corepack prepare pnpm@latest --activate
 
-# Set environment variables
 ARG DATABASE_URL
 ENV DATABASE_URL=$DATABASE_URL
 
@@ -25,59 +8,52 @@ ARG NEXTAUTH_SECRET
 ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
 
 ARG ENCRYPTION_KEY
-ENV ENCRYPTION_KEY=$ENCRYPTION_KEY
+ENV ENCRYPTION_KEY=b19a492fe2a9c01debe543f945d8481728e126904f5b54acc53eb0936748fb02
 
 WORKDIR /app
 
 COPY . .
-
-# Create an empty .env file
 RUN touch /app/apps/web/.env
 
-# Install your application dependencies
 RUN pnpm install
 
 # Build the project
 RUN pnpm post-install --filter=web...
 RUN pnpm turbo run build --filter=web...
 
-# Use a different base image for the runner stage
 FROM node:18-alpine AS runner
-
-# Enable corepack and prepare pnpm
 RUN corepack enable && corepack prepare pnpm@latest --activate
 
-# Copy configuration files and built artifacts from the installer stage
+# Don't run production as root
+# RUN addgroup --system --gid 1001 nodejs
+# RUN adduser --system --uid 1001 nextjs
+# USER nextjs
+
+WORKDIR /home/nextjs
+
 COPY --from=installer /app/apps/web/next.config.mjs .
 COPY --from=installer /app/apps/web/package.json .
 
-# Copy the built application files
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
 COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
 COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
 COPY --from=installer --chown=nextjs:nodejs /app/packages/database/schema.prisma ./packages/database/schema.prisma
 COPY --from=installer --chown=nextjs:nodejs /app/packages/database/migrations ./packages/database/migrations
+COPY --from=installer --chown=nextjs:nodejs /app/docker/cronjobs /etc/crontabs/root
 
 EXPOSE 3000
 
+RUN chmod u+s /usr/bin/crontab
+
 ENV HOSTNAME "0.0.0.0"
 
-# Install cron and set up cron jobs as root user
-USER root
-
-RUN apk --no-cache add dcron
-
-# Create a cron directory inside the container
-RUN mkdir /cron
-
-# Copy all the cron job YAML files
-COPY .github/workflows/cron-* /cron/
-
-# Copy your entrypoint.sh script into the container
-COPY /apps/web/entrypoint.sh /entrypoint.sh
-
-# Make the script executable
-RUN chmod +x /entrypoint.sh
-
-# Run entrypoint.sh as the root user
-CMD ["/entrypoint.sh"]
+CMD if [ "$NEXTAUTH_SECRET" != "RANDOM_STRING" ]; then \
+        pnpm dlx prisma migrate deploy && \
+        (crond -f -d 8 &) && \
+        node apps/web/server.js; \
+    else \
+        echo "ERROR: Please set a value for NEXTAUTH_SECRET in your docker compose variables!"; \
+        exit 1; \
+    fi
