feat: pass hardcoded placeholder env values at buildtime

diff --git a/apps/web/Dockerfile b/apps/web/Dockerfile
--- a/apps/web/Dockerfile
+++ b/apps/web/Dockerfile
@@ -26,18 +26,13 @@ RUN apk update && apk add --no-cache g++ cmake make gcc python3 openssl-dev jq
 # Install Supercronic (cron for containers without super user privileges)
 RUN apk add --no-cache curl \
     && curl -fsSLo /tmp/supercronic \
-       "https://github.com/aptible/supercronic/releases/download/v0.2.27/supercronic-linux-amd64" \
+    "https://github.com/aptible/supercronic/releases/download/v0.2.27/supercronic-linux-amd64" \
     && chmod +x /tmp/supercronic
 
-# Set environment variables
-ARG DATABASE_URL
-ENV DATABASE_URL=$DATABASE_URL
-
-ARG NEXTAUTH_SECRET
-ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
-
-ARG ENCRYPTION_KEY
-ENV ENCRYPTION_KEY=$ENCRYPTION_KEY
+# Set hardcoded environment variables
+ENV DATABASE_URL="placeholder_for_build@database.url"
+ENV NEXTAUTH_SECRET="placeholder_for_build_nextauth_secret"
+ENV ENCRYPTION_KEY="placeholder_for_build_encryption_key"
 
 ARG NEXT_PUBLIC_SENTRY_DSN
 
@@ -99,9 +94,9 @@ VOLUME /home/nextjs/apps/web/uploads/
 CMD PRISMA_VERSION=$(cat prisma_version.txt) && \
     supercronic -quiet /app/docker/cronjobs & \
     if [ "$NEXTAUTH_SECRET" != "RANDOM_STRING" ]; then \
-        pnpm dlx prisma@$PRISMA_VERSION migrate deploy && \
-        exec node apps/web/server.js; \
+    pnpm dlx prisma@$PRISMA_VERSION migrate deploy && \
+    exec node apps/web/server.js; \
     else \
-        echo "ERROR: Please set a value for NEXTAUTH_SECRET in your docker compose variables!" >&2; \
-        exit 1; \
+    echo "ERROR: Please set a value for NEXTAUTH_SECRET in your docker compose variables!" >&2; \
+    exit 1; \
     fi
