change yml

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -60,26 +60,40 @@ jobs:
         run: |
           NODE_ENV=test pnpm start --filter=@formbricks/web > app.log 2>&1 &
           echo $! > app.pid
-
-  wait-for-app:
-    runs-on: ubuntu-latest
-    needs: start-app
-    steps:
-      - name: Wait for App
-        run: |
           for attempt in {1..20}; do
             if [ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000/health) -eq 200 ]; then
-              echo "Ready"
+              echo "Application is ready."
               break
             fi
-            echo "Waiting..."
+            echo "Still waiting for the application to be ready..."
             sleep 10
           done
-          cat app.log  # Optionally print the complete log file again at the end.
+          if [ $attempt -eq 20 ]; then
+            echo "Application failed to start in time."
+            cat app.log
+            exit 1
+          fi
+          cat app.log
+
+  # wait-for-app:
+  #   runs-on: ubuntu-latest
+  #   needs: start-app
+  #   steps:
+  #     - name: Wait for App
+  #       run: |
+  #         for attempt in {1..20}; do
+  #           if [ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000/health) -eq 200 ]; then
+  #             echo "Ready"
+  #             break
+  #           fi
+  #           echo "Waiting..."
+  #           sleep 10
+  #         done
+  #         cat app.log  # Optionally print the complete log file again at the end.
 
   run-tests:
     runs-on: ubuntu-latest
-    needs: wait-for-app
+    needs: start-app
     steps:
       - name: Install dependencies
         run: pnpm install
