remove pid waiting

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -60,17 +60,19 @@ jobs:
       - name: Run App
         run: |
           NODE_ENV=test pnpm start --filter=@formbricks/web &
-          APP_PID=$!
           sleep 10  # Optional: gives some buffer for the app to start
-          for attempt in {1..20}; do
+          for attempt in {1..10}; do
             if [ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000/health) -eq 200 ]; then
               echo "Application is ready."
               break
             fi
-            echo "Still waiting for the application to be ready..."
-            sleep 10
-          done
-          wait $APP_PID
+            if [ $attempt -eq 10 ]; then
+              echo "Application failed to start in time."
+              exit 1
+            fi
+              echo "Still waiting for the application to be ready..."
+              sleep 10
+            done
 
       - name: Test Serve endpoints
         run: |
